### ISSUE TITLE
Live Demo is Down!

### ISSUE THREAD

**Issue by sudoevans** [ivqonsanada/phive#43]
Getting a 403 Error  when I try to access [Live Demo](https://phive.ivqonsanada.com/)

**Comment by Muzam3l** [comment]
I'm waiting for the demo site to restart for 2 months, Do you have any updates on when it'll back up? :(

**Comment by ivqonsanada** [comment]
Hi @Muzam3l, sorry to hear that, several people actually also DM me on LinkedIn related to this too, ⁣ :disappointed: . 

Let me try to deploy it this week, and implement task scheduling to reset the database every some time. 

The app itself really need to be updated, Vue 2 no longer officially maintained by the end of last year. Need to migrate it to Vue 3, also seems Laravel 11 will come soon this Q1  :thinking:

**Comment by mobsikx** [comment]
Awwww, it's a pity you don't take it more seriously. It's been almost a year since they reported the demo site was down.

**Comment by ivqonsanada** [comment]
Hi, its Up! @Muzam3l @mobsikx @sudoevans, I also update the config to the newest and fix ~80 vulnerabilities
